name: ChatScribe
version: 1.2.1
main: aliuly\chatscribe\Main
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
load: POSTWORLD
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/ChatScribe

description: Logs chats and commands
author: aliuly

commands:
  log:
    description: Enable/disable logging
    usage: "/log [on|off]"
    permission: chatscribe.cmd
  spy:
    description: spy on a player in-game
    usage: "/spy [start|stop|ls] [player]"
    permission: chatscribe.spy

permissions:
  chatscribe.cmd:
    default: op
    description: "Enable logging"
  chatscribe.privacy:
    default: false
    description: "No logging"
  chatscribe.spy:
    default: false
    description: "Allow to spy on users in-game"
