name: AutoHeal
description: Basic Auto-Healing Plugin
version: 1.0.3
author: aliuly
main: aliuly\autoheal\Main
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
load: POSTWORLD

permissions:
    autoheal:
        default: false
        description: "Players with this permission can auto-heal"
